-- Tonight's Sweat Card RPC
-- ============================================================
-- Returns the structured Sweat Card row for ET-today. Generated by
-- mlb_pipeline/generate_sweat_card.py — combines POTD + Dawg + top
-- props (with audited tier rates) + bucket angle + skip alerts into
-- a single JSON payload the app renders at the top of the MLB tab.
--
-- Apply via Supabase SQL editor.

CREATE OR REPLACE FUNCTION get_todays_sweat_card()
RETURNS SETOF jerry_cache
LANGUAGE SQL
STABLE
AS $$
  SELECT * FROM jerry_cache
  WHERE game_id = 'sweat_card_' || slate_date_et()::TEXT
  LIMIT 1;
$$;

GRANT EXECUTE ON FUNCTION get_todays_sweat_card() TO anon, authenticated;
