-- NFL prop playbook signals (2026-08-17).
--
-- Ports the MLB prop signal set to NFL by mapping to NFL's own JSONB
-- flag names (l5_form, _edge_pct, _projected_value, projection,
-- opp_matchup). MLB signals like `batter_l7_hot` won't fire on NFL
-- because NFL uses different key names — this seeds NFL-native signals.
--
-- Depends on: 20260817_prop_playbook_infra.sql
-- Ready for NFL Week 1 (early September 2026). Playbook has 3 NFL
-- signals seeded before this (from earlier POC): player_l10_vs_line_extreme,
-- legacy_conviction_strong, projection_edge_supports/strong (from proj migration).
-- This adds 5 more so NFL playbook has ≥8 signals when props start firing.

DELETE FROM public.signal_sources
 WHERE sport = 'NFL'
   AND class IN ('prop_form', 'prop_trend', 'prop_matchup', 'prop_model')
   AND origin = 'SEEDED_NFL_817';

INSERT INTO public.signal_sources
  (signal_key, sport, class, market_scope, subject_scope,
   condition_expr, side_expr, strength_expr,
   display_prose_template, description, enabled, origin)
VALUES
  -- ── NFL form signals ──────────────────────────────────────────
  ('nfl_l5_form_supports', 'NFL', 'prop_trend', '*', 'prop',
   'isinstance(p.get("signals"), dict) and "l5_form" in p["signals"]',
   '"BACK"',
   '0.5',
   'L5 form supports pick direction — {l5_form}',
   'NFL L5 rolling form matches prop direction (generated by nfl_generate_props)',
   true, 'SEEDED_NFL_817'),

  ('nfl_edge_pct_supports', 'NFL', 'prop_model', '*', 'prop',
   'isinstance(p.get("signals"), dict) and "_edge_pct" in p["signals"] and p["signals"]["_edge_pct"] is not None and float(p["signals"]["_edge_pct"]) >= 0.10',
   '"BACK"',
   'min(float(p["signals"]["_edge_pct"]) * 2.0, 1.0)',
   'model projection edge {_edge_pct} supports direction',
   'NFL projected value diverges from book line in direction of pick (>= 10%)',
   true, 'SEEDED_NFL_817'),

  ('nfl_edge_pct_strong', 'NFL', 'prop_model', '*', 'prop',
   'isinstance(p.get("signals"), dict) and "_edge_pct" in p["signals"] and p["signals"]["_edge_pct"] is not None and float(p["signals"]["_edge_pct"]) >= 0.25',
   '"BACK"',
   'min(float(p["signals"]["_edge_pct"]) * 1.5, 1.0)',
   'strong projection edge {_edge_pct}',
   'NFL projected value 25%+ off book line — model conviction',
   true, 'SEEDED_NFL_817'),

  ('nfl_edge_pct_opposes', 'NFL', 'prop_model', '*', 'prop',
   'isinstance(p.get("signals"), dict) and "_edge_pct" in p["signals"] and p["signals"]["_edge_pct"] is not None and float(p["signals"]["_edge_pct"]) <= -0.15',
   '"FADE"',
   'min(abs(float(p["signals"]["_edge_pct"])) * 2.0, 1.0)',
   'projection opposes direction — {_edge_pct}',
   'NFL projected value contradicts pick direction — fire FADE',
   true, 'SEEDED_NFL_817'),

  ('nfl_opp_matchup_favorable', 'NFL', 'prop_matchup', '*', 'prop',
   'isinstance(p.get("signals"), dict) and "opp_matchup" in p["signals"] and p["signals"]["opp_matchup"] is not None and "no opp" not in str(p["signals"]["opp_matchup"]) and ("weak" in str(p["signals"]["opp_matchup"]) or "poor" in str(p["signals"]["opp_matchup"]) or "bottom" in str(p["signals"]["opp_matchup"]))',
   '"BACK" if p.get("direction") == "over" else "FADE"',
   '0.5',
   'opposing matchup favorable — {opp_matchup}',
   'Opp defense weak against this position — boost OVER props',
   true, 'SEEDED_NFL_817');

NOTIFY pgrst, 'reload schema';
