-- UFC v1 model predictions (stored picks)
-- ============================================================
-- Server-side prediction storage for upcoming UFC cards. Generated by
-- ufc_score_card.py on Thursday cron post-card-scraper. App reads via
-- get_todays_ufc_picks() RPC (no client-side prediction).
--
-- One row per fight on the upcoming card. Re-keyed each cron so latest
-- card always overwrites.
--
-- Apply via Supabase SQL editor.

CREATE TABLE IF NOT EXISTS ufc_picks (
  id BIGSERIAL PRIMARY KEY,
  event_name TEXT NOT NULL,
  event_date DATE NOT NULL,
  fight_order INT,                       -- 1 = main event

  fighter_a TEXT NOT NULL,
  fighter_b TEXT NOT NULL,
  fighter_a_url TEXT,
  fighter_b_url TEXT,

  -- Model outputs
  p_winner_a NUMERIC,                    -- P(fighter_a wins)
  p_method_ko NUMERIC,
  p_method_sub NUMERIC,
  p_method_dec NUMERIC,
  p_distance NUMERIC,
  p_round_1 NUMERIC,
  p_round_2 NUMERIC,
  p_round_3 NUMERIC,
  p_round_4 NUMERIC,
  p_round_5 NUMERIC,

  -- Conviction tier (for UI rendering)
  conviction_winner INT,                  -- 0-100 derived from edge vs 50% baseline
  tier_winner TEXT,                       -- 'PRIME', 'STRONG', 'LEAN', or null
  recommended_side TEXT,                  -- 'a' or 'b' (model's pick)

  -- Edge calls for prop markets (when above threshold)
  edge_method TEXT,                       -- 'KO/TKO', 'SUB', 'DEC' if a method exceeds threshold
  edge_distance TEXT,                     -- 'OVER', 'UNDER' for goes-distance

  generated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE (event_name, fighter_a, fighter_b)
);

CREATE INDEX IF NOT EXISTS idx_ufc_picks_event ON ufc_picks(event_date DESC, fight_order ASC);

-- Returns picks for the upcoming/most-recent UFC event (no slate-date math
-- needed since cards are once weekly; latest stored card is "today's").
CREATE OR REPLACE FUNCTION get_todays_ufc_picks()
RETURNS SETOF ufc_picks
LANGUAGE SQL
STABLE
AS $$
  SELECT * FROM ufc_picks
  WHERE event_date = (SELECT MAX(event_date) FROM ufc_picks)
  ORDER BY fight_order ASC;
$$;

GRANT EXECUTE ON FUNCTION get_todays_ufc_picks() TO anon, authenticated;
